<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\SubCategoryInput;
use App\Models\SubCategory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\SubCategoryInput>
 */
class SubCategoryInputFactory extends Factory
{
    protected $model = SubCategoryInput::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $types = ['text', 'number', 'select', 'date'];
        $type = $this->faker->randomElement($types);
        
        $name = str_replace(' ', '', $this->faker->unique()->words(2, true));
        $placeholder = $this->generateArabicPlaceholder($name, $type);

        return [
            'sub_category_id' => SubCategory::inRandomOrder()->value('id') ?? SubCategory::factory()->create()->id,
            'name' => $name,
            'type' => $type,
            'placeholder' => $placeholder,
            'is_readonly' => $this->faker->boolean(10),
            'is_required' => $this->faker->boolean(60),
        ];
    }

    /**
     * Generate Arabic placeholder based on name and type
     */
    private function generateArabicPlaceholder(string $name, string $type): string
    {
        $arabicPlaceholders = [
            'name' => 'الاسم',
            'title' => 'العنوان',
            'description' => 'الوصف',
            'price' => 'السعر',
            'amount' => 'المبلغ',
            'quantity' => 'الكمية',
            'count' => 'العدد',
            'date' => 'التاريخ',
            'time' => 'الوقت',
            'location' => 'الموقع',
            'address' => 'العنوان',
            'phone' => 'رقم الهاتف',
            'email' => 'البريد الإلكتروني',
            'website' => 'الموقع الإلكتروني',
            'category' => 'الفئة',
            'type' => 'النوع',
            'status' => 'الحالة',
            'color' => 'اللون',
            'size' => 'الحجم',
            'weight' => 'الوزن',
            'brand' => 'العلامة التجارية',
            'model' => 'الموديل',
            'year' => 'السنة',
            'condition' => 'الحالة',
            'notes' => 'ملاحظات',
            'comment' => 'تعليق',
            'message' => 'رسالة',
            'text' => 'نص',
            'number' => 'رقم',
            'value' => 'القيمة',
            'rate' => 'التقييم',
            'score' => 'النقاط',
            'level' => 'المستوى',
            'grade' => 'الدرجة',
            'age' => 'العمر',
            'height' => 'الطول',
            'width' => 'العرض',
            'length' => 'الطول',
            'depth' => 'العمق',
            'area' => 'المساحة',
            'volume' => 'الحجم',
            'capacity' => 'السعة',
            'speed' => 'السرعة',
            'distance' => 'المسافة',
            'duration' => 'المدة',
            'period' => 'الفترة',
            'interval' => 'الفاصل',
            'range' => 'النطاق',
            'limit' => 'الحد',
            'maximum' => 'الحد الأقصى',
            'minimum' => 'الحد الأدنى',
            'average' => 'المتوسط',
            'total' => 'المجموع',
            'sum' => 'المجموع',
            'result' => 'النتيجة',
            'output' => 'المخرجات',
            'input' => 'المدخلات',
            'data' => 'البيانات',
            'information' => 'المعلومات',
            'details' => 'التفاصيل',
            'specifications' => 'المواصفات',
            'features' => 'المميزات',
            'benefits' => 'الفوائد',
            'advantages' => 'المزايا',
            'disadvantages' => 'العيوب',
            'pros' => 'الإيجابيات',
            'cons' => 'السلبيات',
            'options' => 'الخيارات',
            'choices' => 'الاختيارات',
            'alternatives' => 'البدائل',
            'variants' => 'المتغيرات',
            'versions' => 'الإصدارات',
            'editions' => 'الطبعات',
            'releases' => 'الإصدارات',
            'updates' => 'التحديثات',
            'upgrades' => 'الترقيات',
            'improvements' => 'التحسينات',
            'enhancements' => 'التحسينات',
            'modifications' => 'التعديلات',
            'changes' => 'التغييرات',
            'adjustments' => 'التعديلات',
            'settings' => 'الإعدادات',
            'configurations' => 'التكوينات',
            'preferences' => 'التفضيلات',
            'options' => 'الخيارات',
            'selections' => 'الاختيارات',
            'filters' => 'المرشحات',
            'criteria' => 'المعايير',
            'standards' => 'المعايير',
            'requirements' => 'المتطلبات',
            'conditions' => 'الشروط',
            'terms' => 'الشروط',
            'rules' => 'القواعد',
            'regulations' => 'اللوائح',
            'policies' => 'السياسات',
            'procedures' => 'الإجراءات',
            'processes' => 'العمليات',
            'methods' => 'الطرق',
            'techniques' => 'التقنيات',
            'strategies' => 'الاستراتيجيات',
            'approaches' => 'المناهج',
            'solutions' => 'الحلول',
            'answers' => 'الإجابات',
            'responses' => 'الردود',
            'replies' => 'الردود',
            'feedback' => 'التعليقات',
            'reviews' => 'المراجعات',
            'ratings' => 'التقييمات',
            'evaluations' => 'التقييمات',
            'assessments' => 'التقييمات',
            'analyses' => 'التحليلات',
            'reports' => 'التقارير',
            'summaries' => 'الملخصات',
            'overviews' => 'النظرات العامة',
            'introductions' => 'المقدمات',
            'conclusions' => 'الاستنتاجات',
            'recommendations' => 'التوصيات',
            'suggestions' => 'الاقتراحات',
            'advice' => 'النصائح',
            'tips' => 'النصائح',
            'hints' => 'التلميحات',
            'clues' => 'الأدلة',
            'evidence' => 'الأدلة',
            'proof' => 'الدليل',
            'verification' => 'التحقق',
            'validation' => 'التحقق',
            'confirmation' => 'التأكيد',
            'approval' => 'الموافقة',
            'authorization' => 'التفويض',
            'permission' => 'الإذن',
            'access' => 'الوصول',
            'entry' => 'الدخول',
            'login' => 'تسجيل الدخول',
            'logout' => 'تسجيل الخروج',
            'register' => 'التسجيل',
            'signup' => 'التسجيل',
            'signin' => 'تسجيل الدخول',
            'signout' => 'تسجيل الخروج',
            'account' => 'الحساب',
            'profile' => 'الملف الشخصي',
            'user' => 'المستخدم',
            'customer' => 'العميل',
            'client' => 'العميل',
            'member' => 'العضو',
            'participant' => 'المشارك',
            'contributor' => 'المساهم',
            'author' => 'المؤلف',
            'creator' => 'المنشئ',
            'owner' => 'المالك',
            'manager' => 'المدير',
            'administrator' => 'المدير',
            'admin' => 'المدير',
            'supervisor' => 'المشرف',
            'director' => 'المدير',
            'leader' => 'القائد',
            'head' => 'الرئيس',
            'chief' => 'الرئيس',
            'boss' => 'الرئيس',
            'employee' => 'الموظف',
            'worker' => 'العامل',
            'staff' => 'الموظفين',
            'team' => 'الفريق',
            'group' => 'المجموعة',
            'organization' => 'المنظمة',
            'company' => 'الشركة',
            'business' => 'الأعمال',
            'enterprise' => 'المؤسسة',
            'corporation' => 'الشركة',
            'firm' => 'الشركة',
            'agency' => 'الوكالة',
            'department' => 'القسم',
            'division' => 'القسم',
            'section' => 'القسم',
            'unit' => 'الوحدة',
            'branch' => 'الفرع',
            'office' => 'المكتب',
            'location' => 'الموقع',
            'place' => 'المكان',
            'venue' => 'المكان',
            'site' => 'الموقع',
            'area' => 'المنطقة',
            'region' => 'المنطقة',
            'zone' => 'المنطقة',
            'district' => 'المنطقة',
            'neighborhood' => 'الحي',
            'street' => 'الشارع',
            'road' => 'الطريق',
            'avenue' => 'الشارع',
            'boulevard' => 'الشارع',
            'lane' => 'الزقاق',
            'alley' => 'الزقاق',
            'building' => 'المبنى',
            'house' => 'المنزل',
            'home' => 'المنزل',
            'apartment' => 'الشقة',
            'flat' => 'الشقة',
            'room' => 'الغرفة',
            'hall' => 'القاعة',
            'hallway' => 'الممر',
            'corridor' => 'الممر',
            'entrance' => 'المدخل',
            'exit' => 'المخرج',
            'door' => 'الباب',
            'window' => 'النافذة',
            'gate' => 'البوابة',
            'fence' => 'السور',
            'wall' => 'الجدار',
            'floor' => 'الأرضية',
            'ceiling' => 'السقف',
            'roof' => 'السقف',
            'basement' => 'القبو',
            'attic' => 'العلية',
            'garage' => 'المرآب',
            'parking' => 'موقف السيارات',
            'garden' => 'الحديقة',
            'yard' => 'الفناء',
            'patio' => 'الفناء',
            'balcony' => 'الشرفة',
            'terrace' => 'الشرفة',
            'deck' => 'الشرفة',
            'porch' => 'الشرفة',
            'veranda' => 'الشرفة',
            'pool' => 'المسبح',
            'spa' => 'السبا',
            'sauna' => 'الساونا',
            'gym' => 'الصالة الرياضية',
            'fitness' => 'اللياقة البدنية',
            'exercise' => 'التمرين',
            'workout' => 'التمرين',
            'training' => 'التدريب',
            'practice' => 'الممارسة',
            'rehearsal' => 'البروفة',
            'performance' => 'الأداء',
            'show' => 'العرض',
            'display' => 'العرض',
            'exhibition' => 'المعرض',
            'fair' => 'المعرض',
            'market' => 'السوق',
            'store' => 'المتجر',
            'shop' => 'المتجر',
            'mall' => 'المول',
            'center' => 'المركز',
            'plaza' => 'الساحة',
            'square' => 'الميدان',
            'park' => 'الحديقة',
            'playground' => 'ملعب الأطفال',
            'stadium' => 'الملعب',
            'arena' => 'الساحة',
            'field' => 'الميدان',
            'court' => 'الملعب',
            'track' => 'المضمار',
            'course' => 'المسار',
            'path' => 'المسار',
            'trail' => 'المسار',
            'route' => 'الطريق',
            'way' => 'الطريق',
            'direction' => 'الاتجاه',
            'destination' => 'الوجهة',
            'target' => 'الهدف',
            'goal' => 'الهدف',
            'objective' => 'الهدف',
            'purpose' => 'الغرض',
            'aim' => 'الهدف',
            'intention' => 'النية',
            'plan' => 'الخطة',
            'strategy' => 'الاستراتيجية',
            'tactic' => 'التكتيك',
            'method' => 'الطريقة',
            'approach' => 'المنهج',
            'technique' => 'التقنية',
            'skill' => 'المهارة',
            'ability' => 'القدرة',
            'talent' => 'الموهبة',
            'gift' => 'الهدية',
            'present' => 'الهدية',
            'reward' => 'المكافأة',
            'prize' => 'الجائزة',
            'award' => 'الجائزة',
            'honor' => 'الشرف',
            'recognition' => 'التقدير',
            'appreciation' => 'التقدير',
            'gratitude' => 'الامتنان',
            'thanks' => 'الشكر',
            'thank' => 'شكر',
            'welcome' => 'مرحباً',
            'greeting' => 'التحية',
            'salutation' => 'التحية',
            'farewell' => 'الوداع',
            'goodbye' => 'وداعاً',
            'bye' => 'وداعاً',
            'hello' => 'مرحباً',
            'hi' => 'مرحباً',
            'hey' => 'مرحباً',
            'good' => 'جيد',
            'bad' => 'سيء',
            'great' => 'رائع',
            'excellent' => 'ممتاز',
            'outstanding' => 'متميز',
            'superb' => 'رائع',
            'wonderful' => 'رائع',
            'amazing' => 'مذهل',
            'awesome' => 'رائع',
            'fantastic' => 'رائع',
            'incredible' => 'لا يصدق',
            'unbelievable' => 'لا يصدق',
            'remarkable' => 'ملحوظ',
            'extraordinary' => 'استثنائي',
            'exceptional' => 'استثنائي',
            'special' => 'خاص',
            'unique' => 'فريد',
            'rare' => 'نادر',
            'uncommon' => 'غير شائع',
            'unusual' => 'غير عادي',
            'marketable' => 'قابل للتسويق',
            'commercial' => 'تجاري',
            'currency' => 'العملة',
           
        ];

        // Try to find a matching Arabic placeholder based on the name
        $nameLower = strtolower($name);
        foreach ($arabicPlaceholders as $english => $arabic) {
            if (strpos($nameLower, $english) !== false) {
                return $arabic;
            }
        }

        // If no match found, generate a generic Arabic placeholder based on type
        $genericPlaceholders = [
            'text' => 'أدخل النص هنا',
            'number' => 'أدخل الرقم هنا',
            'select' => 'اختر من القائمة',
            'date' => 'اختر التاريخ',
        ];

        return $genericPlaceholders[$type] ?? 'أدخل القيمة هنا';
    }

    /**
     * State for select type inputs
     */
    public function select(): self
    {
        return $this->state(fn () => [
            'type' => 'select',
        ]);
    }
}


